# Generated by Django 5.0 on 2024-07-26 12:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=30)),
                ('subjectImage', models.ImageField(upload_to='subjectimages')),
                ('subjectDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseImage', models.ImageField(upload_to='subjectimages')),
                ('courseName', models.CharField(max_length=30)),
                ('coursePrice', models.PositiveIntegerField(help_text='Price in dollars')),
                ('courseDuration', models.DurationField(default=datetime.timedelta(seconds=19200))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
            ],
        ),
    ]
