# Generated by Django 5.0 on 2024-08-01 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_coursename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subjects', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects', verbose_name='Course Subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.DurationField(default=datetime.timedelta(seconds=19200), verbose_name='Course Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(help_text='image size 100 by 100', upload_to='subjectimages', verbose_name='Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePrice',
            field=models.PositiveIntegerField(help_text='Price in dollars', verbose_name='Course Price'),
        ),
    ]
